# -*- python -*-

from Defaults import *

IMAGE_LOGOS = '/mailman/images/mailman/'
MAILMAN_SITE_LIST = 'mailman'
MTA='Manual'
SMTPHOST= 'postfix-mailcow'

DEFAULT_ADMIN_MEMBER_CHUNKSIZE = 100
DEFAULT_ARCHIVE = Off
DEFAULT_ARCHIVE_PRIVATE = 1
DEFAULT_ARCHIVE_VOLUME_FREQUENCY = 2
DEFAULT_DIGESTABLE = No
DEFAULT_DMARC_MODERATION_ACTION = 0
DEFAULT_DMARC_NONE_MODERATION_ACTION = Yes
DEFAULT_DMARC_QUARENTINE_MODERATION_ACTION = Yes
DEFAULT_EMAIL_HOST = '%DEFAULT_EMAIL_HOST%'
DEFAULT_FIRST_STRIP_REPLY_TO = No
DEFAULT_FROM_IS_LIST = No
DEFAULT_INCLUDE_LIST_POST_HEADER = Yes
DEFAULT_INCLUDE_RFC2369_HEADERS = Yes
DEFAULT_INCLUDE_SENDER_HEADER = No
DEFAULT_LIST_ADVERTISED = No
DEFAULT_MAX_MESSAGE_SIZE = 0
DEFAULT_MAX_NUM_RECIPIENTS = 50
DEFAULT_MSG_FOOTER = ''
DEFAULT_MSG_HEADER = ''
DEFAULT_REPLY_GOES_TO_LIST = 0
DEFAULT_SCRUB_NONDIGEST = No
DEFAULT_SEND_GOODBYE_MSG = No
DEFAULT_SEND_REMINDERS = No
DEFAULT_SEND_WELCOME_MSG = No
DEFAULT_SERVER_LANGUAGE = 'cs'
DEFAULT_SUBJECT_PREFIX = ''
DEFAULT_SUBSCRIBE_POLICY = 2
DEFAULT_URL_HOST = '%DEFAULT_URL_HOST%'
DEFAULT_URL_PATTERN = 'https://%s/mailman/'

add_language('cs', 'Czech', 'utf-8', 'ltr')
